import { createApp } from 'vue';
import App from './App.vue';
import router from './router/index.js';
import { createI18n } from 'vue-i18n';
import './assets/theme.css';

const messages = {
  zh: {
    welcome: '欢迎来到Looge幸运团购',
    switchLang: '切换语言',
    confirm: '确认',
    home: '首页',
    group: '拼团区',
    login: '登录',
    register: '注册',
    share: '分享',
    profile: '个人中心',
    announcement: '公告',
    lottery: '抽奖',
    invite: '邀请注册',
    account: '账号',
    password: '密码',
    confirmPassword: '确认密码',
    nickname: '昵称',
    inviteCode: '邀请码',
    inviteCount: '邀请人数',
    teamCount: '团队人数',
    balance: '余额',
    financeRecords: '财务记录',
    groupList: '参与拼团',
    prizeList: '奖品',
    prize: '奖品',
    wallet: '钱包',
    withdraw: '提款',
    recharge: '充值',
    message: '消息',
    carousel: '轮播图',
    marquee: '跑马灯公告',
    copyLink: '复制链接',
    adText: '加入Looge幸运团购，拼团抽奖，赢大奖，邀请好友一起参与更有分红！',
    noData: '暂无数据',
    submit: '提交',
    back: '返回',
    groupPurchase: '团购抽奖',
    shareEarn: '分享赚钱',
    vipPrivilege: 'VIP特权',
    personalCenter: '个人中心',
    participants: '参与人数',
    timeLeft: '剩余时间',
    minutes: '分钟',
    joinGroup: '参与拼团',
    progress: '进度',
    region: '区域',
    zone10k: '10000区',
    zone30k: '30000区', 
    zone80k: '80000区',
    zone150k: '150000区',
    zone300k: '300000区',
    zone600k: '600000区',
    zone1000k: '1000000区',
    admin: '管理员',
    adminLogin: '管理员登录',
    adminAccount: '管理员账号',
    adminPassword: '管理员密码',
    adminLevel: '权限级别',
    superAdmin: '超级管理员',
    normalAdmin: '普通管理员',
    viewAdmin: '查看权限',
    securityNotice: '安全提醒',
    adminSecurityText: '管理员登录将被记录，请确保在安全环境下操作',
    logging: '登录中...',
    userLogin: '用户登录',
    adminFeatures: '管理功能',
    prizeManagement: '奖品管理',
    messageManagement: '消息管理',
    userManagement: '用户管理',
    dataAnalysis: '数据分析',
    pleaseComplete: '请完善信息',
    loginSuccess: '登录成功！',
    loginFailed: '登录失败',
    registerSuccess: '注册成功！',
    registerFailed: '注册失败',
    passwordMismatch: '密码不一致',
    inviteCodeInvalid: '邀请码格式错误',
    adminLoginSuccess: '管理员登录成功！',
    adminLoginFailed: '管理员账号或密码错误',
    adminLoginError: '登录出现错误，请稍后重试'
  },
  en: {
    welcome: 'Welcome to Looge Lucky Group Purchase',
    switchLang: 'Switch Language',
    confirm: 'Confirm',
    home: 'Home',
    group: 'Group Purchase',
    login: 'Login',
    register: 'Register',
    share: 'Share',
    profile: 'Profile',
    announcement: 'Announcement',
    lottery: 'Lottery',
    invite: 'Invite to Register',
    account: 'Account',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    nickname: 'Nickname',
    inviteCode: 'Invite Code',
    inviteCount: 'Invite Count',
    teamCount: 'Team Count',
    balance: 'Balance',
    financeRecords: 'Finance Records',
    groupList: 'Group Purchase',
    prizeList: 'Prizes',
    prize: 'Prize',
    wallet: 'Wallet',
    withdraw: 'Withdraw',
    recharge: 'Recharge',
    message: 'Message',
    carousel: 'Carousel',
    marquee: 'Marquee',
    copyLink: 'Copy Link',
    adText: 'Join Looge Lucky Group Purchase, group lottery, win big prizes, invite friends to participate for more dividends!',
    noData: 'No Data',
    submit: 'Submit',
    back: 'Back',
    groupPurchase: 'Group Purchase Lottery',
    shareEarn: 'Share & Earn',
    vipPrivilege: 'VIP Privilege',
    personalCenter: 'Personal Center',
    participants: 'Participants',
    timeLeft: 'Time Left',
    minutes: 'minutes',
    joinGroup: 'Join Group',
    progress: 'Progress',
    region: 'Region',
    zone10k: '10K Zone',
    zone30k: '30K Zone',
    zone80k: '80K Zone', 
    zone150k: '150K Zone',
    zone300k: '300K Zone',
    zone600k: '600K Zone',
    zone1000k: '1M Zone',
    admin: 'Admin',
    adminLogin: 'Admin Login',
    adminAccount: 'Admin Account',
    adminPassword: 'Admin Password',
    adminLevel: 'Permission Level',
    superAdmin: 'Super Admin',
    normalAdmin: 'Normal Admin',
    viewAdmin: 'View Permission',
    securityNotice: 'Security Notice',
    adminSecurityText: 'Admin login will be recorded, please ensure you operate in a secure environment',
    logging: 'Logging in...',
    userLogin: 'User Login',
    adminFeatures: 'Admin Features',
    prizeManagement: 'Prize Management',
    messageManagement: 'Message Management',
    userManagement: 'User Management',
    dataAnalysis: 'Data Analysis',
    pleaseComplete: 'Please complete the information',
    loginSuccess: 'Login successful!',
    loginFailed: 'Login failed',
    registerSuccess: 'Registration successful!',
    registerFailed: 'Registration failed',
    passwordMismatch: 'Passwords do not match',
    inviteCodeInvalid: 'Invalid invite code format',
    adminLoginSuccess: 'Admin login successful!',
    adminLoginFailed: 'Admin account or password incorrect',
    adminLoginError: 'Login error, please try again later'
  },
  es: {
    welcome: 'Bienvenido a Looge Compra de Grupo de la Suerte',
    switchLang: 'Cambiar idioma',
    confirm: 'Confirmar',
    home: 'Inicio',
    group: 'Grupo',
    login: 'Iniciar sesión',
    register: 'Registrarse',
    share: 'Compartir',
    profile: 'Perfil',
    announcement: 'Anuncio',
    lottery: 'Sorteo',
    invite: 'Invitar a registrar',
    account: 'Cuenta',
    password: 'Contraseña',
    confirmPassword: 'Confirmar contraseña',
    nickname: 'Apodo',
    inviteCode: 'Código de invitación',
    inviteCount: 'Número de invitados',
    teamCount: 'Número de equipo',
    balance: 'Saldo',
    financeRecords: 'Registros financieros',
    groupList: 'Participación en grupo',
    prizeList: 'Premios',
    prize: 'Premio',
    wallet: 'Billetera',
    withdraw: 'Retirar',
    recharge: 'Recargar',
    message: 'Mensaje',
    carousel: 'Carrusel',
    marquee: 'Anuncio',
    copyLink: 'Copiar enlace',
    adText: '¡Únete a Looge, compra grupal de la suerte, lotería grupal, gana grandes premios, invita a tus amigos para más dividendos!',
    noData: 'Sin datos',
    submit: 'Enviar',
    back: 'Volver',
    groupPurchase: 'Lotería de Compra Grupal',
    shareEarn: 'Compartir y Ganar',
    vipPrivilege: 'Privilegio VIP',
    personalCenter: 'Centro Personal',
    participants: 'Participantes',
    timeLeft: 'Tiempo Restante',
    minutes: 'minutos',
    joinGroup: 'Unirse al Grupo',
    progress: 'Progreso',
    region: 'Región',
    zone10k: 'Zona 10K',
    zone30k: 'Zona 30K',
    zone80k: 'Zona 80K',
    zone150k: 'Zona 150K',
    zone300k: 'Zona 300K',
    zone600k: 'Zona 600K',
    zone1000k: 'Zona 1M',
    admin: 'Administrador',
    adminLogin: 'Inicio de sesión de administrador',
    adminAccount: 'Cuenta de administrador',
    adminPassword: 'Contraseña de administrador',
    adminLevel: 'Nivel de permisos',
    superAdmin: 'Super administrador',
    normalAdmin: 'Administrador normal',
    viewAdmin: 'Permiso de vista',
    securityNotice: 'Aviso de seguridad',
    adminSecurityText: 'El inicio de sesión del administrador será registrado, asegúrese de operar en un entorno seguro',
    logging: 'Iniciando sesión...',
    userLogin: 'Inicio de sesión de usuario',
    adminFeatures: 'Funciones de administrador',
    prizeManagement: 'Gestión de premios',
    messageManagement: 'Gestión de mensajes',
    userManagement: 'Gestión de usuarios',
    dataAnalysis: 'Análisis de datos',
    pleaseComplete: 'Por favor complete la información',
    loginSuccess: '¡Inicio de sesión exitoso!',
    loginFailed: 'Error de inicio de sesión',
    registerSuccess: '¡Registro exitoso!',
    registerFailed: 'Error de registro',
    passwordMismatch: 'Las contraseñas no coinciden',
    inviteCodeInvalid: 'Formato de código de invitación inválido',
    adminLoginSuccess: '¡Inicio de sesión de administrador exitoso!',
    adminLoginFailed: 'Cuenta o contraseña de administrador incorrecta',
    adminLoginError: 'Error de inicio de sesión, inténtelo de nuevo más tarde'
  }
};

// Get saved language or default to Chinese
const savedLanguage = localStorage.getItem('language') || 'zh';

const i18n = createI18n({
  locale: savedLanguage,
  fallbackLocale: 'en',
  messages,
});

const app = createApp(App);
app.use(router);
app.use(i18n);
app.mount('#app');